baseURL: https://gitjournal.io/
languageCode: en-us
title: GitJournal
Paginate: 100

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true

disableKinds:
  - taxonomy
  - taxonomyTerm

params:
  navbar:
    - title: Pricing
      Permalink: /pricing
    - title: Docs
      Permalink: /support
    - title: Changelog
      Permalink: /changelog
    - title: Blog
      Permalink: /blog
    - title: About
      Permalink: /about

  footer:
    - title: GitJournal
      links:
        - title: About Us
          Permalink: /about
        - title: Contribute
          Permalink: /contribute
        - title: FAQ
          Permalink: /support
        - title: Privacy
          Permalink: /privacy
        - title: Roadmap
          Permalink: https://github.com/GitJournal/GitJournal/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
    # Add Changelog
    # Add Screenshots
    - title: Social
      links:
        - title: Twitter
          Permalink: https://twitter.com/GitJournal_io
        - title: Discord
          Permalink: https://discord.gg/abBwyEK
        - title: Reddit
          Permalink: https://reddit.com/r/GitJournal
        - title: Mastodon
          Permalink: https://fosstodon.org/@gitjournal
          rel: me
        - title: Newsletter
          Permalink: /newsletter
    - title: Spread the Word
      links:
        - title: Star the Project on GitHub
          Permalink: https://github.com/GitJournal/GitJournal
        #- title: Featured on Product Hunt
        #  Permalink: /
        - title: Like Us on Alternative To
          Permalink: https://alternativeto.net/software/gitjournal/
        #- title: Like Us on Slant
        #  Permalink: / -> Requires someone to put me on Slant
        - title: Stack us on YourStack
          Permalink: https://yourstack.com/products/gitjournal
