name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.74.3"
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.10.1"

      - run: npm ci
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: GitJournal/GitJournal.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: vhanda
          user_email: me@vhanda.in
          publish_branch: master
        #   cname: example.com
